version: '3'


services:
  db:
    image: postgres:latest
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: always


  bookstore-api:
    image: bookstore-api
    build:
      context: .
      dockerfile: Dockerfile
    command: initial
    env_file:
      - .env
    ports:
      - "127.0.0.1:8200:8000"
    volumes:
      - ./bookstore:/opt/app/bookstore
      - /opt/docker/bookstore/log:/opt/app/log/
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:

networks:
  default:
    name: bookstore-api-network