"""empty message

Revision ID: d59804eaa242
Revises: 74cefdbba28d
Create Date: 2025-05-06 10:56:41.896262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd59804eaa242'
down_revision: Union[str, None] = '74cefdbba28d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('tags', sa.Column('discount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'discount')
    op.drop_column('books', 'price')
    # ### end Alembic commands ###
