"""empty message

Revision ID: ccc406f402bc
Revises: d59804eaa242
Create Date: 2025-05-06 12:26:18.720294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccc406f402bc'
down_revision: Union[str, None] = 'd59804eaa242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('id_book', sa.Integer(), nullable=False))
    op.drop_constraint('carts_id_books_fkey', 'carts', type_='foreignkey')
    op.create_foreign_key(None, 'carts', 'books', ['id_book'], ['id'])
    op.drop_column('carts', 'id_books')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('id_books', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.create_foreign_key('carts_id_books_fkey', 'carts', 'books', ['id_books'], ['id'])
    op.drop_column('carts', 'id_book')
    # ### end Alembic commands ###
